FROM tensorflow/tensorflow:1.15.5-gpu-py3-jupyter

MAINTAINER Mischan Vali Pour

WORKDIR /

RUN python -m pip install matplotlib pandas scipy scikit-learn seaborn ##add python modules which are not inside the image


